/**
 * @module pdfService
 * @description Generates monthly PDF digest reports using pdfkit.
 * Creates a professional 3-page PDF with summary stats, bill table,
 * and anomaly details. Designed to be uploaded to Google Drive.
 */

const PDFDocument = require('pdfkit');

/**
 * Generates a monthly digest PDF as a Buffer.
 *
 * @param {Object} data - Digest data object
 * @param {string} data.month - Month name (e.g., "April")
 * @param {string} data.year - Year (e.g., "2026")
 * @param {Array<Object>} data.bills - All bills for the month
 * @param {Array<Object>} data.alerts - All alerts for the month
 * @param {Array<Object>} data.anomalies - Anomaly details
 * @returns {Promise<Buffer>} PDF file as a Buffer
 */
async function generateDigest(data) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `BillGuard Digest — ${data.month} ${data.year}`,
          Author: 'BillGuard AI'
        }
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ─── PAGE 1: Summary ───────────────────────────────────────
      renderSummaryPage(doc, data);

      // ─── PAGE 2: Bills Table ───────────────────────────────────
      doc.addPage();
      renderBillsTable(doc, data);

      // ─── PAGE 3: Anomalies Detail ─────────────────────────────
      doc.addPage();
      renderAnomaliesPage(doc, data);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Renders the summary page with key stats.
 * @param {PDFDocument} doc - PDFKit document instance
 * @param {Object} data - Digest data
 */
function renderSummaryPage(doc, data) {
  const bills = data.bills || [];
  const alerts = data.alerts || [];
  const anomalies = data.anomalies || [];

  const totalAmount = bills.reduce((sum, b) => sum + (parseFloat(b.amount) || 0), 0);
  const moneyAtRisk = anomalies
    .filter(a => a.type === 'duplicate' || a.type === 'price_hike')
    .reduce((sum, a) => sum + (parseFloat(a.amount) || 0), 0);

  // Header
  doc.fontSize(28).fillColor('#0F172A')
    .text('BillGuard', 50, 50, { continued: true })
    .fillColor('#10B981').text('AI');

  doc.moveDown(0.3);
  doc.fontSize(12).fillColor('#64748B')
    .text('Monthly Financial Digest');

  // Title
  doc.moveDown(1.5);
  doc.fontSize(24).fillColor('#0F172A')
    .text(`${data.month} ${data.year}`, { align: 'center' });

  doc.moveDown(2);

  // Stats grid
  const stats = [
    { label: 'Total Bills Detected', value: bills.length.toString(), color: '#6366F1' },
    { label: 'Total Amount Tracked', value: `₹${totalAmount.toLocaleString()}`, color: '#10B981' },
    { label: 'Anomalies Flagged', value: anomalies.length.toString(), color: '#F59E0B' },
    { label: 'Money at Risk', value: `₹${moneyAtRisk.toLocaleString()}`, color: '#EF4444' },
    { label: 'Alerts Sent', value: alerts.length.toString(), color: '#6366F1' }
  ];

  let y = doc.y;
  for (const stat of stats) {
    // Stat card background
    doc.roundedRect(50, y, 495, 50, 8)
      .fillAndStroke('#F8FAFC', '#E2E8F0');

    doc.fontSize(14).fillColor(stat.color)
      .text(stat.value, 70, y + 10, { width: 140 });
    doc.fontSize(11).fillColor('#64748B')
      .text(stat.label, 70, y + 30, { width: 200 });

    y += 64;
  }

  // Footer
  doc.fontSize(9).fillColor('#94A3B8')
    .text('Generated by BillGuard AI', 50, 750, { align: 'center' });
}

/**
 * Renders the bills table page.
 * @param {PDFDocument} doc - PDFKit document instance
 * @param {Object} data - Digest data
 */
function renderBillsTable(doc, data) {
  const bills = (data.bills || [])
    .sort((a, b) => (parseFloat(b.amount) || 0) - (parseFloat(a.amount) || 0));

  doc.fontSize(18).fillColor('#0F172A')
    .text('Bills Breakdown', 50, 50);
  doc.moveDown(1);

  // Table header
  const colWidths = [140, 80, 70, 80, 125];
  const headers = ['Merchant', 'Amount', 'Type', 'Date', 'Status'];
  let y = doc.y;

  doc.fontSize(10).fillColor('#64748B');
  let x = 50;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x, y, { width: colWidths[i] });
    x += colWidths[i];
  }

  y += 20;
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#E2E8F0').stroke();
  y += 8;

  // Table rows
  doc.fontSize(10).fillColor('#334155');
  for (const bill of bills.slice(0, 30)) { // Cap at 30 rows per page
    if (y > 720) {
      doc.addPage();
      y = 50;
    }

    x = 50;
    const row = [
      (bill.merchant || 'Unknown').substring(0, 22),
      `${bill.currency || '₹'} ${bill.amount || 0}`,
      bill.type || 'unknown',
      bill.detectedDate || '',
      bill.anomalyFlag ? '⚠ Flagged' : '✓ Normal'
    ];

    // Alternate row background
    if (bills.indexOf(bill) % 2 === 0) {
      doc.rect(50, y - 4, 495, 20).fill('#F8FAFC');
    }

    doc.fillColor(bill.anomalyFlag ? '#F59E0B' : '#334155');
    for (let i = 0; i < row.length; i++) {
      doc.text(row[i], x, y, { width: colWidths[i] });
      x += colWidths[i];
    }
    y += 22;
  }
}

/**
 * Renders the anomalies detail page.
 * @param {PDFDocument} doc - PDFKit document instance
 * @param {Object} data - Digest data
 */
function renderAnomaliesPage(doc, data) {
  const anomalies = data.anomalies || [];

  doc.fontSize(18).fillColor('#0F172A')
    .text('Anomalies & Alerts', 50, 50);
  doc.moveDown(1);

  if (anomalies.length === 0) {
    doc.fontSize(13).fillColor('#10B981')
      .text('✓ No anomalies detected this month. Your finances look clean!');
    return;
  }

  let y = doc.y;
  for (const anomaly of anomalies) {
    if (y > 680) {
      doc.addPage();
      y = 50;
    }

    const typeColors = {
      price_hike: '#EF4444',
      duplicate: '#EF4444',
      trial_expiry: '#F59E0B',
      forgotten_sub: '#F59E0B'
    };

    const color = typeColors[anomaly.type] || '#6366F1';

    // Anomaly card
    doc.roundedRect(50, y, 495, 70, 8)
      .fillAndStroke('#FAFAFA', color);

    doc.fontSize(12).fillColor(color)
      .text(anomaly.type?.replace(/_/g, ' ').toUpperCase() || 'ALERT', 65, y + 10);

    doc.fontSize(10).fillColor('#334155')
      .text(anomaly.message || '', 65, y + 30, { width: 460 });

    y += 84;
  }

  // Footer
  doc.fontSize(9).fillColor('#94A3B8')
    .text('Generated by BillGuard AI', 50, 750, { align: 'center' });
}

module.exports = { generateDigest };
